language: node_js  #设置语言

node_js: stable  #设置相应的版本

# Handle git submodules yourself
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - git config --global user.name "xurongyang"  #修改name
  - git config --global user.email "rongyangxu@gmail.com"  #修改email
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  - npm install hexo-cli -g
  - npm install  #安装hexo及插件

script:
  - hexo cl  #清除
  - hexo g  #生成

after_script:
  - git config --global user.name "xurongyang"  #修改name
  - git config --global user.email "rongyangxu@gmail.com"  #修改email
  - sed -i'' "s~git@github.com:xurongyang/xurongyang.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/xurongyang/xurongyang.github.io.git~" _config.yml
  - hexo deploy
#  - cd ./public
#  - git init
#  - git config user.name "xurongyang"  #修改name
#  - git config user.email "rongyangxu@gmail.com"  #修改email
#  - git add .
#  - git commit -m "update"
#  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称

branches:
  only:
    - hexo  #只监测hexo分支，hexo是我的分支的名称，可根据自己情况设置
env:
 global:
   - GH_REF: github.com/xurongyang/xurongyang.github.io.git  #设置GH_REF，注意更改yourname
